// import { Noto_Sans } from "next/font/google";
// import "./globals.css";
// import LayoutWrapper from "@/components/LayoutWrapper";
// import "react-quill/dist/quill.snow.css";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
// const notoSans = Noto_Sans({
//   variable: "--font-noto-sans",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// export const metadata = {
//   title: "Empowerers",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${notoSans.variable} antialiased`}>
//         <LayoutWrapper>{children}

//         <ToastContainer />


//         </LayoutWrapper>
//       </body>
//     </html>
//   );
// }
"use client";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";
import "react-quill/dist/quill.snow.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { usePathname } from "next/navigation";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// export const metadata = {
//   title: "Empowerers",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Add your page here
  const noLayoutRoutes = ["/ebay-crash-course"];

  const isNoLayout = noLayoutRoutes.includes(pathname);

  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        {isNoLayout ? (
          <>
            {children}
            <ToastContainer />
          </>
        ) : (
          <LayoutWrapper>
            {children}
            <ToastContainer />
          </LayoutWrapper>
        )}
      </body>
    </html>
  );
}
